# Generated by Django 2.0.4 on 2018-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=20)),
                ('upswd', models.CharField(max_length=50)),
                ('uemail', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=20, null=True)),
                ('isActivate', models.BooleanField(default=True)),
            ],
        ),
    ]
